use crate::utils;
use clap::Parser;
use serde_json::Value;
use std::process::exit;

#[derive(Parser, Debug)]
pub struct Args {
    /// Input file (optional). If not provided, reads from stdin (pipe)
    #[arg(short, long)]
    input: Option<String>,

    /// Struct name
    #[arg(short, long, default_value = "AutoGenerated")]
    name: String,

    /// Use json tags
    #[arg(short, long)]
    json: bool,
}

pub fn run(args: &Args, copy: bool) {
    match generate_code(args) {
        Ok(go_code) => {
            utils::emit(&go_code, copy).unwrap_or_else(|e| {
                eprintln!("Error: {}", e);
                exit(1);
            });
        }
        Err(e) => {
            eprintln!("Error: {}", e);
            exit(1);
        }
    }
}

fn generate_code(args: &Args) -> Result<String, String> {
    let json_str = utils::read_stdin_or_file(&args.input)?;

    if json_str.trim().is_empty() {
        return Err("Empty input provided. Pipe JSON or use --input file.json".to_string());
    }

    let value = serde_json::from_str::<Value>(&json_str)
        .map_err(|e| format!("Failed to parse JSON: {}", e))?;
    Ok(format!(
        "type {} {}",
        args.name,
        json_value_to_go_type(&value, args.json, 0)?
    ))
}

fn json_value_to_go_type(
    value: &Value,
    with_json_tags: bool,
    indent: u64,
) -> Result<String, String> {
    render_type(&infer_type(value)?, with_json_tags, indent)
}

#[derive(Debug, Clone, PartialEq)]
enum GoType {
    /// No type information yet (empty object/array); identity for merging
    Unknown,
    Null,
    Any,
    Bool,
    Int,
    Float,
    /// Numbers mixed with numeric strings ("321", "3.0", ...)
    Number,
    /// A string that parses as a JSON number; renders as string but
    /// merges with numbers into json.Number
    NumericString,
    Str,
    Ptr(Box<GoType>),
    Slice(Box<GoType>),
    Map(Box<GoType>),
    Struct(Vec<(String, GoType)>),
}

fn infer_type(value: &Value) -> Result<GoType, String> {
    match value {
        Value::Null => Ok(GoType::Null),
        Value::Bool(_) => Ok(GoType::Bool),
        Value::Number(n) => {
            if n.is_f64() {
                Ok(GoType::Float)
            } else {
                Ok(GoType::Int)
            }
        }
        Value::String(s) => {
            if serde_json::from_str::<serde_json::Number>(s).is_ok() {
                Ok(GoType::NumericString)
            } else {
                Ok(GoType::Str)
            }
        }
        Value::Array(items) => {
            let elem = merge_all(items.iter().map(infer_type))?.unwrap_or(GoType::Unknown);
            Ok(GoType::Slice(Box::new(elem)))
        }
        Value::Object(map) => {
            if map.is_empty() {
                return Ok(GoType::Map(Box::new(GoType::Unknown)));
            }
            let mut fields: Vec<(String, GoType)> = Vec::with_capacity(map.len());
            for (k, v) in map {
                fields.push((k.clone(), infer_type(v)?));
            }
            // A keyed collection ({"data": {...}, "data2": {...}}) rather
            // than a record: every value is itself an object
            if map.len() >= 2 && map.values().all(|v| v.is_object()) {
                let value_type =
                    merge_all(fields.into_iter().map(|(_, t)| Ok(t)))?.unwrap_or(GoType::Any);
                Ok(GoType::Map(Box::new(value_type)))
            } else {
                Ok(GoType::Struct(fields))
            }
        }
    }
}

fn merge_all<I>(types: I) -> Result<Option<GoType>, String>
where
    I: Iterator<Item = Result<GoType, String>>,
{
    let mut acc: Option<GoType> = None;
    for t in types {
        let t = t?;
        acc = Some(match acc {
            None => t,
            Some(prev) => merge_types(prev, t)?,
        });
    }
    Ok(acc)
}

fn merge_types(a: GoType, b: GoType) -> Result<GoType, String> {
    use GoType::*;
    if a == b {
        return Ok(a);
    }
    match (a, b) {
        (Unknown, t) | (t, Unknown) => Ok(t),
        (Null, t) | (t, Null) => match t {
            Any => Ok(Any),
            Ptr(inner) => Ok(Ptr(inner)),
            other => Ok(Ptr(Box::new(other))),
        },
        (Any, _) | (_, Any) => Ok(Any),
        (Ptr(x), Ptr(y)) => wrap_ptr(merge_types(*x, *y)?),
        (Ptr(x), y) | (y, Ptr(x)) => wrap_ptr(merge_types(*x, y)?),
        (Int, Float) | (Float, Int) => Ok(Float),
        (Int, Number) | (Number, Int) | (Float, Number) | (Number, Float) => Ok(Number),
        (Int, NumericString)
        | (NumericString, Int)
        | (Float, NumericString)
        | (NumericString, Float)
        | (Number, NumericString)
        | (NumericString, Number) => Ok(Number),
        (Str, NumericString) | (NumericString, Str) => Ok(Str),
        (Slice(x), Slice(y)) => Ok(Slice(Box::new(merge_types(*x, *y)?))),
        (Map(x), Map(y)) => Ok(Map(Box::new(merge_types(*x, *y)?))),
        (Struct(f1), Struct(f2)) => merge_structs(f1, f2),
        (Map(m), Struct(f)) | (Struct(f), Map(m)) => {
            let mut merged = *m;
            for (_, t) in f {
                merged = merge_types(merged, t)?;
            }
            Ok(Map(Box::new(merged)))
        }
        _ => Ok(Any),
    }
}

fn wrap_ptr(t: GoType) -> Result<GoType, String> {
    match t {
        // any already covers nil
        GoType::Unknown | GoType::Null | GoType::Any => Ok(GoType::Any),
        GoType::Ptr(inner) => Ok(GoType::Ptr(inner)),
        other => Ok(GoType::Ptr(Box::new(other))),
    }
}

fn merge_structs(f1: Vec<(String, GoType)>, f2: Vec<(String, GoType)>) -> Result<GoType, String> {
    let mut k1: Vec<&str> = f1.iter().map(|(k, _)| k.as_str()).collect();
    let mut k2: Vec<&str> = f2.iter().map(|(k, _)| k.as_str()).collect();
    k1.sort_unstable();
    k2.sort_unstable();
    if k1 == k2 {
        let mut by_key: std::collections::HashMap<String, GoType> = f2.into_iter().collect();
        let mut fields = Vec::with_capacity(f1.len());
        for (k, t) in f1 {
            let t2 = by_key
                .remove(&k)
                .ok_or_else(|| format!("Internal error: missing key \"{}\" while merging", k))?;
            let merged = merge_types(t, t2)?;
            fields.push((k, merged));
        }
        return Ok(GoType::Struct(fields));
    }

    // Different keys with only scalar values: a keyed collection, not a record
    if f1.iter().chain(f2.iter()).all(|(_, t)| is_scalar(t)) {
        let value_type =
            merge_all(f1.into_iter().chain(f2).map(|(_, t)| Ok(t)))?.unwrap_or(GoType::Any);
        return Ok(GoType::Map(Box::new(value_type)));
    }

    // Different keys with nested values: a record where some fields are
    // optional, so fields missing on either side become pointers
    let mut by_key: std::collections::HashMap<String, GoType> = std::collections::HashMap::new();
    let mut order2 = Vec::with_capacity(f2.len());
    for (k, t) in f2 {
        order2.push(k.clone());
        by_key.insert(k, t);
    }
    let mut fields = Vec::new();
    for (k, t) in f1 {
        let merged = match by_key.remove(&k) {
            Some(t2) => merge_types(t, t2)?,
            None => wrap_ptr(t)?,
        };
        fields.push((k, merged));
    }
    for k in order2 {
        if let Some(t) = by_key.remove(&k) {
            fields.push((k, wrap_ptr(t)?));
        }
    }
    Ok(GoType::Struct(fields))
}

/// A leaf type (possibly behind a pointer): anything but a struct, map or slice
fn is_scalar(t: &GoType) -> bool {
    match t {
        GoType::Ptr(inner) => is_scalar(inner),
        GoType::Struct(_) | GoType::Map(_) | GoType::Slice(_) => false,
        _ => true,
    }
}

fn render_type(t: &GoType, with_json_tags: bool, indent: u64) -> Result<String, String> {
    match t {
        GoType::Unknown | GoType::Null | GoType::Any => Ok("any".to_string()),
        GoType::Bool => Ok("bool".to_string()),
        GoType::Int => Ok("int".to_string()),
        GoType::Float => Ok("float64".to_string()),
        GoType::Number => Ok("json.Number".to_string()),
        GoType::Str | GoType::NumericString => Ok("string".to_string()),
        GoType::Ptr(inner) => Ok(format!("*{}", render_type(inner, with_json_tags, indent)?)),
        GoType::Slice(inner) => Ok(format!("[]{}", render_type(inner, with_json_tags, indent)?)),
        GoType::Map(inner) => Ok(format!(
            "map[string]{}",
            render_type(inner, with_json_tags, indent)?
        )),
        GoType::Struct(fields) => render_struct(fields, with_json_tags, indent),
    }
}

fn render_struct(
    fields: &[(String, GoType)],
    with_json_tags: bool,
    indent: u64,
) -> Result<String, String> {
    let field_pad = "    ".repeat(indent as usize + 1);
    let close_pad = "    ".repeat(indent as usize);
    let mut lines = vec!["struct {".to_string()];
    // Consecutive single-line fields are aligned together; a nested
    // struct breaks the alignment block (gofmt behavior)
    let mut block: Vec<(String, String, &str)> = Vec::new();

    for (key, t) in fields {
        let name = make_field_name(key)?;
        let type_str = render_type(t, with_json_tags, indent + 1)?;
        if type_str.contains('\n') {
            flush_block(&mut lines, &mut block, &field_pad, with_json_tags)?;
            let mut line = format!("{}{} {}", field_pad, name, type_str);
            if with_json_tags {
                check_tag(key)?;
                line.push_str(&format!(" `json:\"{}\"`", key));
            }
            lines.push(line);
        } else {
            block.push((name, type_str, key));
        }
    }
    flush_block(&mut lines, &mut block, &field_pad, with_json_tags)?;
    lines.push(format!("{}}}", close_pad));
    Ok(lines.join("\n"))
}

fn flush_block(
    lines: &mut Vec<String>,
    block: &mut Vec<(String, String, &str)>,
    pad: &str,
    with_json_tags: bool,
) -> Result<(), String> {
    if block.is_empty() {
        return Ok(());
    }
    let name_w = block
        .iter()
        .map(|(n, _, _)| n.chars().count())
        .max()
        .unwrap_or(0);
    let type_w = block
        .iter()
        .map(|(_, t, _)| t.chars().count())
        .max()
        .unwrap_or(0);
    for (name, type_str, key) in block.drain(..) {
        if with_json_tags {
            check_tag(key)?;
            lines.push(format!(
                "{}{:<name_w$} {:<type_w$} `json:\"{}\"`",
                pad, name, type_str, key
            ));
        } else {
            lines.push(format!("{}{:<name_w$} {}", pad, name, type_str));
        }
    }
    Ok(())
}

fn check_tag(s: &str) -> Result<(), String> {
    if s.chars()
        .any(|c| c == ',' || c == '\\' || c == '"' || c == '\'')
    {
        return Err(format!(
            "Tag \"{}\" can not contain \",\" or \"\\\" or \"\"\" or \"\'\", you have to implement custom unmarshaler for this field.",
            s
        ));
    }
    Ok(())
}

fn make_field_name(s: &str) -> Result<String, String> {
    let result: String = s
        .trim()
        .split(|c: char| c.is_ascii_punctuation() || c.is_whitespace())
        .filter(|w| !w.is_empty())
        .flat_map(split_case_words)
        .map(|word| pascalize(&word))
        .collect();

    match result.chars().next() {
        None => Err(format!("Cannot make field name for key: \"{}\"", s)),
        Some(c) => {
            if !c.is_uppercase() {
                Err(format!(
                    "Cannot make field name for key (first char is not alphabetic): \"{}\"",
                    s
                ))
            } else {
                Ok(result)
            }
        }
    }
}

/// Split a word at camelCase/PascalCase boundaries: before an uppercase
/// following a lowercase or digit, and before the last uppercase of an
/// acronym run followed by a lowercase (HTTPServer -> HTTP, Server)
fn split_case_words(word: &str) -> Vec<String> {
    let chars: Vec<char> = word.chars().collect();
    let mut words = Vec::new();
    let mut cur = String::new();
    for (i, &c) in chars.iter().enumerate() {
        if !cur.is_empty() && c.is_uppercase() {
            let prev = chars[i - 1];
            let next_is_lower = chars.get(i + 1).is_some_and(|n| n.is_lowercase());
            if prev.is_lowercase() || prev.is_numeric() || (prev.is_uppercase() && next_is_lower) {
                words.push(std::mem::take(&mut cur));
            }
        }
        cur.push(c);
    }
    if !cur.is_empty() {
        words.push(cur);
    }
    words
}

/// Uppercase the first letter, keeping the rest of the word intact;
/// fully-uppercase words (acronyms) are title-cased so XML becomes Xml
fn pascalize(word: &str) -> String {
    let is_acronym =
        word.chars().count() > 1 && word.chars().all(|c| c.is_uppercase() || c.is_numeric());
    let word = if is_acronym {
        word.to_lowercase()
    } else {
        word.to_string()
    };
    let mut chars = word.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => first.to_uppercase().chain(chars).collect(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generate(json: &str, with_json_tags: bool) -> String {
        let value: Value = serde_json::from_str(json).unwrap();
        json_value_to_go_type(&value, with_json_tags, 0).unwrap()
    }

    #[test]
    fn test_scalars() {
        assert_eq!(generate("null", true), "any");
        assert_eq!(generate("true", true), "bool");
        assert_eq!(generate("123", true), "int");
        assert_eq!(generate("3.0", true), "float64");
        assert_eq!(generate("\"hello\"", true), "string");
        assert_eq!(generate("\"321\"", true), "string");
    }

    #[test]
    fn test_arrays_number_patterns() {
        assert_eq!(generate("[1, 2, 3]", true), "[]int");
        assert_eq!(generate("[1, 2.0]", true), "[]float64");
        assert_eq!(generate("[1, 2, \"321\"]", true), "[]json.Number");
        assert_eq!(generate("[1.0, 2.0, \"321.0\"]", true), "[]json.Number");
        assert_eq!(generate("[1.1, 2.0, \"3210\"]", true), "[]json.Number");
        assert_eq!(generate("[\"321\", \"322\"]", true), "[]string");
        assert_eq!(generate("[\"321\", \"abc\"]", true), "[]string");
        assert_eq!(generate("[1, \"abc\"]", true), "[]any");
        assert_eq!(generate("[]", true), "[]any");
    }

    #[test]
    fn test_arrays_null_makes_pointer() {
        assert_eq!(generate("[1, 2, null]", true), "[]*int");
        assert_eq!(generate("[1, 2, \"3210\", null]", true), "[]*json.Number");
        assert_eq!(generate("[null, null]", true), "[]any");
        assert_eq!(generate("[1, \"abc\", null]", true), "[]any");
    }

    #[test]
    fn test_object_with_differing_keys_is_map() {
        assert_eq!(
            generate(r#"[{"a": "x"}, {"b": "y", "c": "z"}]"#, true),
            "[]map[string]string"
        );
        assert_eq!(
            generate(r#"[{"a": "x"}, {"b": 1}]"#, true),
            "[]map[string]any"
        );
        assert_eq!(
            generate(r#"[{"a": "x"}, {"b": null}, null]"#, true),
            "[]*map[string]*string"
        );
    }

    #[test]
    fn test_object_of_objects_is_map() {
        assert_eq!(
            generate(r#"{"data": {"a": 1}, "data2": {"a": 2}}"#, true),
            "map[string]struct {\n    A int `json:\"a\"`\n}"
        );
        // a single wrapped object stays a struct
        assert_eq!(
            generate(r#"{"data": {"a": 1}}"#, true),
            "struct {\n    Data struct {\n        A int `json:\"a\"`\n    } `json:\"data\"`\n}"
        );
    }

    #[test]
    fn test_struct_alignment_blocks() {
        let out = generate(
            r#"{"a": "x", "bb": 1, "c": {"dd": "y", "e": null}, "ff": [1, 2.0]}"#,
            true,
        );
        let expected = "\
struct {
    A  string `json:\"a\"`
    Bb int    `json:\"bb\"`
    C struct {
        Dd string `json:\"dd\"`
        E  any    `json:\"e\"`
    } `json:\"c\"`
    Ff []float64 `json:\"ff\"`
}";
        assert_eq!(out, expected);
    }

    #[test]
    fn test_no_tags() {
        let out = generate(r#"{"a": "x", "bb": 1, "c": {"d": null}}"#, false);
        let expected = "\
struct {
    A  string
    Bb int
    C struct {
        D any
    }
}";
        assert_eq!(out, expected);
    }

    #[test]
    fn test_merge_nullability() {
        let out = generate(
            r#"[
                {"a": "x", "b": null, "c": [1,2], "d": {"e": "v"}, "f": 1},
                {"a": null, "b": true, "c": null, "d": null, "f": 2.0}
            ]"#,
            true,
        );
        let expected = "\
[]struct {
    A *string `json:\"a\"`
    B *bool   `json:\"b\"`
    C *[]int  `json:\"c\"`
    D *struct {
        E string `json:\"e\"`
    } `json:\"d\"`
    F float64 `json:\"f\"`
}";
        assert_eq!(out, expected);
    }

    #[test]
    fn test_differing_keys_with_nested_values_stay_struct() {
        // Objects that share most keys but miss a few, and hold nested
        // values, are records with optional fields — not maps
        let out = generate(
            r#"[
                {"symbol": "A", "isin": "GB1", "levels": [{"m": 0.1}], "schedules": {}},
                {"symbol": "B", "lastTradingTime": "t", "levels": [{"m": 0.2}], "schedules": {"eu": {"r": 1}, "us": {"r": 2}}}
            ]"#,
            true,
        );
        let expected = "\
[]struct {
    Symbol string  `json:\"symbol\"`
    Isin   *string `json:\"isin\"`
    Levels []struct {
        M float64 `json:\"m\"`
    } `json:\"levels\"`
    Schedules map[string]struct {
        R int `json:\"r\"`
    } `json:\"schedules\"`
    LastTradingTime *string `json:\"lastTradingTime\"`
}";
        assert_eq!(out, expected);
    }

    #[test]
    fn test_empty_containers_merge_neutrally() {
        assert_eq!(generate(r#"[[], [1, 2]]"#, true), "[][]int");
        assert_eq!(
            generate(r#"[{"t": []}, {"t": ["a"]}]"#, false),
            "[]struct {\n    T []string\n}"
        );
        assert_eq!(
            generate(
                r#"[{"m": {}}, {"m": {"a": {"r": 1}, "b": {"r": 2}}}]"#,
                false
            ),
            "[]struct {\n    M map[string]struct {\n        R int\n    }\n}"
        );
    }

    #[test]
    fn test_incompatible_types_become_any() {
        let out = generate(r#"[{"a": 3}, {"a": "value"}]"#, true);
        assert_eq!(out, "[]struct {\n    A any `json:\"a\"`\n}");
    }

    #[test]
    fn test_bad_tag_returns_err() {
        let value: Value = serde_json::from_str(r#"{"a,b": 1}"#).unwrap();
        assert!(json_value_to_go_type(&value, true, 0).is_err());
        // without tags the key is never written, so it is fine
        assert!(json_value_to_go_type(&value, false, 0).is_ok());
    }

    #[test]
    fn test_bad_field_name_returns_err() {
        let value: Value = serde_json::from_str(r#"{"___": 1}"#).unwrap();
        assert!(json_value_to_go_type(&value, true, 0).is_err());
    }

    #[test]
    fn test_check_tag_err() {
        assert!(check_tag("hello,world").is_err());
        assert!(check_tag("hello\\world").is_err());
        assert!(check_tag("hello\"world").is_err());
        assert!(check_tag("hello'world").is_err());
    }

    #[test]
    fn test_check_tag_ok() {
        assert!(check_tag("hello world").is_ok());
        assert!(check_tag("hello...world").is_ok());
        assert!(check_tag("hello/world").is_ok());
    }

    #[test]
    fn test_make_field_name() {
        assert_eq!(make_field_name("heLLo_world").unwrap(), "HeLLoWorld");
        assert_eq!(make_field_name("hello__world").unwrap(), "HelloWorld");
        assert_eq!(
            make_field_name("XML_HTTP_*()REQUEST").unwrap(),
            "XmlHttpRequest"
        );
        assert_eq!(make_field_name("iPhone").unwrap(), "IPhone");
        assert_eq!(make_field_name("API_V2_RESPONSE").unwrap(), "ApiV2Response");
        assert_eq!(make_field_name("user_id").unwrap(), "UserId");
        assert_eq!(make_field_name("max-100-items").unwrap(), "Max100Items");
        assert_eq!(make_field_name("_hello.world_").unwrap(), "HelloWorld");
        assert_eq!(make_field_name("__hEllo.world_").unwrap(), "HElloWorld");
        // camelCase and PascalCase both convert to PascalCase
        assert_eq!(
            make_field_name("lastTradingTime").unwrap(),
            "LastTradingTime"
        );
        assert_eq!(
            make_field_name("LastTradingTime").unwrap(),
            "LastTradingTime"
        );
        assert_eq!(
            make_field_name("fundingRateCoefficient").unwrap(),
            "FundingRateCoefficient"
        );
        assert_eq!(make_field_name("XMLHttpRequest").unwrap(), "XmlHttpRequest");
        assert_eq!(
            make_field_name("numNonContractUnits").unwrap(),
            "NumNonContractUnits"
        );
        assert_eq!(make_field_name("hello").unwrap(), "Hello");
        assert_eq!(make_field_name("a").unwrap(), "A");
        assert_eq!(make_field_name("as用a.sjlk").unwrap(), "As用aSjlk");
    }

    #[test]
    fn test_empty_input() {
        assert!(make_field_name("").is_err());
    }

    #[test]
    fn test_non_alph_on_first_char() {
        assert!(make_field_name("0asjlk").is_err());
        assert!(make_field_name("用asjlk").is_err());
    }

    #[test]
    fn test_only_separators() {
        assert!(make_field_name("{").is_err());
        assert!(make_field_name(",{ \x09").is_err());
        assert!(make_field_name("_").is_err());
        assert!(make_field_name(".").is_err());
        assert!(make_field_name(" ").is_err());
        assert!(make_field_name("-").is_err());
        assert!(make_field_name("___ - .").is_err());
    }
}
