use clap::Parser;
use serde_json::Value;
use std::fs;
use std::io::{self, Read};

#[derive(Parser, Debug)]
pub struct Args {
    /// Input file (optional). If not provided, reads from stdin (pipe)
    #[arg(short, long)]
    input: Option<String>,

    /// Struct name (default: "AutoGenerated")
    #[arg(short, long, default_value = "AutoGenerated")]
    name: String,

    /// Use json tags
    #[arg(short, long)]
    json: bool,
}
pub fn run(args: &Args) {
    let json_str = read_input(&args.input);

    if json_str.trim().is_empty() {
        panic!("Error: Empty input provided. Pipe JSON or use --input file.json");
    }

    match serde_json::from_str::<Value>(&json_str) {
        Ok(value) => {
            let go_code = format!(
                "type {} struct {{\n{}}}\n",
                &args.name,
                json_value_to_go_type(&value, args.json, 1)
            );
            println!("{}", go_code);
        }
        Err(e) => {
            panic!("Failed to parse JSON: {}", e);
        }
    }
}

fn read_input(input_file: &Option<String>) -> String {
    if let Some(file) = input_file {
        fs::read_to_string(file).expect("Failed to read from file")
    } else {
        let mut buffer = String::new();
        io::stdin()
            .read_to_string(&mut buffer)
            .expect("Failed to read from stdin");
        buffer
    }
}

fn json_value_to_go_type(value: &Value, with_json_tags: bool, indent: u64) -> String {
    let _ = (value, with_json_tags, indent);
    String::new() // TODO
}

#[allow(dead_code)]
fn check_tag(s: &str) {
    let mut chars = s.chars();
    loop {
        match chars.next() {
            None => break,
            Some(c) => {
                if c == ',' || c == '\\' || c == '"' || c == '\'' {
                    panic!(
                        "Tag can not contain \",\" or \"\\\", you have to implement custom unmarshaler for this field."
                    );
                }
            }
        }
    }
}

#[allow(dead_code)]
fn make_field_name(s: &str) -> String {
    let result: String = s
        .trim()
        .split(|c: char| c.is_ascii_punctuation() || c.is_whitespace())
        .filter(|w| !w.is_empty())
        .map(|word| {
            let lowered = word.to_lowercase();
            let mut chars = lowered.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().chain(chars).collect(),
            }
        })
        .collect();

    if result.is_empty() {
        panic!("Cannot make field name for key: \"{}\"", s);
    }

    match result.chars().next() {
        None => panic!("Cannot make field name for key: \"{}\"", s),
        Some(c) => {
            if !c.is_alphabetic() {
                panic!(
                    "Cannot make field name for key (first char is not alphabetic): \"{}\"",
                    s
                )
            }
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[should_panic]
    fn test_check_tag_panic() {
        check_tag("hello,world");
        check_tag("hello\\world");
        check_tag("hello\"world");
        check_tag("hello'world");
    }

    #[test]
    fn test_check_tag_ok() {
        check_tag("hello world");
        check_tag("hello...world");
        check_tag("hello/world");
    }

    #[test]
    fn test_make_field_name() {
        assert_eq!(make_field_name("heLLo_world"), "HelloWorld");
        assert_eq!(make_field_name("hello__world"), "HelloWorld");
        assert_eq!(make_field_name("XML_HTTP_*()REQUEST"), "XmlHttpRequest");
        assert_eq!(make_field_name("iPhone"), "Iphone");
        assert_eq!(make_field_name("API_V2_RESPONSE"), "ApiV2Response");
        assert_eq!(make_field_name("user_id"), "UserId");
        assert_eq!(make_field_name("max-100-items"), "Max100Items");
        assert_eq!(make_field_name("_hello.world_"), "HelloWorld");
        assert_eq!(make_field_name("__hEllo.world_"), "HelloWorld");
        assert_eq!(make_field_name("hello"), "Hello");
        assert_eq!(make_field_name("a"), "A");
        assert_eq!(make_field_name("as用a.sjlk"), "As用aSjlk");
    }

    #[test]
    #[should_panic]
    fn test_empty_input() {
        make_field_name("");
    }

    #[test]
    #[should_panic]
    fn test_non_alph_on_first_char() {
        make_field_name("0asjlk");
        make_field_name("用asjlk");
    }

    #[test]
    #[should_panic]
    fn test_only_separators() {
        make_field_name("{");
        make_field_name(",{ \x09");
        make_field_name("_");
        make_field_name(".");
        make_field_name(" ");
        make_field_name("-");
        make_field_name("___ - .");
    }
}
